# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-11-07 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
